# Generated by Django 3.0.8 on 2020-08-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalandrierStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Calandrier Standard',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('charge', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'cours',
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('debut', models.TimeField(blank=True, max_length=100)),
                ('fin', models.TimeField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Créneau',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('chef', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'departement',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_etudiant', models.IntegerField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Classe')),
            ],
            options={
                'verbose_name_plural': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jour',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'niveau',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('capacite', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'salle',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Cours')),
                ('créneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Creneau')),
            ],
            options={
                'verbose_name_plural': 'Seance',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Departement')),
            ],
            options={
                'verbose_name_plural': 'professeur',
            },
        ),
        migrations.CreateModel(
            name='Preferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('créneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Creneau')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Professeur')),
            ],
            options={
                'verbose_name_plural': 'Préferance',
            },
        ),
        migrations.CreateModel(
            name='Matier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Departement')),
            ],
            options={
                'verbose_name_plural': 'matiére',
            },
        ),
        migrations.CreateModel(
            name='IndispoProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('créneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Creneau')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Professeur')),
            ],
            options={
                'verbose_name_plural': 'Indispo Prof',
            },
        ),
        migrations.CreateModel(
            name='IndispoGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('créneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Creneau')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Groupe')),
            ],
            options={
                'verbose_name_plural': 'Indispo Groupe',
            },
        ),
        migrations.CreateModel(
            name='Filier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Departement')),
            ],
            options={
                'verbose_name_plural': 'filiére',
            },
        ),
        migrations.CreateModel(
            name='ExceptionCalandrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True)),
                ('type', models.BooleanField()),
                ('calandrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.CalandrierStandard')),
                ('créneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Creneau')),
            ],
            options={
                'verbose_name_plural': 'éxception Calandrier',
            },
        ),
        migrations.CreateModel(
            name='DetailCalandrier',
            fields=[
                ('id', models.AutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('calandrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.CalandrierStandard')),
                ('créneaux', models.ManyToManyField(to='iscae_emploi.Creneau')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Jour')),
            ],
            options={
                'verbose_name_plural': 'Détail Calandrier',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Groupe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Matier'),
        ),
        migrations.AddField(
            model_name='cours',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Professeur'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Salle'),
        ),
        migrations.AddField(
            model_name='classe',
            name='filier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Filier'),
        ),
        migrations.AddField(
            model_name='classe',
            name='matier_etu',
            field=models.ManyToManyField(to='iscae_emploi.Matier'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Niveau'),
        ),
    ]
