# Generated by Django 3.0.8 on 2020-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='type',
            field=models.CharField(choices=[('CM', 'Cours magistrale'), ('TD', 'Travaux dirigés'), ('TP', 'travaux pratiques')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
