# Generated by Django 3.0.8 on 2020-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indispogroupe',
            name='créneau',
        ),
        migrations.RemoveField(
            model_name='indispoprof',
            name='créneau',
        ),
        migrations.AddField(
            model_name='indispogroupe',
            name='créneaux',
            field=models.ManyToManyField(to='iscae_emploi.Creneau'),
        ),
        migrations.AddField(
            model_name='indispoprof',
            name='créneaux',
            field=models.ManyToManyField(to='iscae_emploi.Creneau'),
        ),
    ]
