# Generated by Django 3.0.8 on 2020-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0002_cours_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='type',
            field=models.CharField(choices=[('Cours magistrale', 'Cours magistrale'), ('Travaux dirigés', 'Travaux dirigés'), ('travaux pratiques', 'travaux pratiques')], max_length=20, unique=True),
        ),
    ]
