# Generated by Django 3.0.8 on 2020-08-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0004_auto_20200810_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calandrierstandard',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cours',
            name='charge',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cours',
            name='groupe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Groupe'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Matier'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cours',
            name='prof',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Professeur'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Salle'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='debut',
            field=models.TimeField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='fin',
            field=models.TimeField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='numero',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='departement',
            name='chef',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='departement',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='departement',
            name='mobile',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='exceptioncalandrier',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='exceptioncalandrier',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='filier',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nombre_etudiant',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='indispogroupe',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='indispoprof',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='jour',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='jour',
            name='numero',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='matier',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='mobile',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='prenom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='salle',
            name='capacite',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
