# Generated by Django 3.0.8 on 2020-08-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0005_auto_20200820_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferance_prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('créneaux', models.ManyToManyField(to='iscae_emploi.Creneau')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Jour')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Professeur')),
            ],
            options={
                'verbose_name_plural': 'Préferance',
            },
        ),
        migrations.AlterField(
            model_name='departement',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Preferance',
        ),
    ]
