# Generated by Django 3.0.8 on 2020-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0006_auto_20200827_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
