# Generated by Django 3.0.8 on 2020-09-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0007_seance_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('cours', 'créneau')},
        ),
    ]
