# Generated by Django 3.0.8 on 2020-09-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0008_auto_20200902_1115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('groupe', 'matier', 'prof', 'salle')},
        ),
        migrations.AlterUniqueTogether(
            name='detailcalandrier',
            unique_together={('jour', 'calandrier')},
        ),
    ]
