# Generated by Django 3.0.8 on 2020-09-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0009_auto_20200902_1125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailcalandrier',
            unique_together={('calandrier', 'jour')},
        ),
    ]
