# Generated by Django 3.0.8 on 2020-09-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0010_auto_20200902_1131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailcalandrier',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('cours', 'créneau', 'date')},
        ),
        migrations.CreateModel(
            name='groupeCHV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Cours')),
                ('créneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Creneau')),
            ],
            options={
                'verbose_name_plural': 'Seance',
                'unique_together': {('cours', 'créneau')},
            },
        ),
    ]
