# Generated by Django 3.0.8 on 2020-10-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0011_auto_20200913_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptioncalandrier',
            name='créneau',
        ),
        migrations.AddField(
            model_name='exceptioncalandrier',
            name='créneau',
            field=models.ManyToManyField(to='iscae_emploi.Creneau'),
        ),
        migrations.DeleteModel(
            name='groupeCHV',
        ),
    ]
