# Generated by Django 3.0.8 on 2020-10-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0012_auto_20201022_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeChevauchement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscae_emploi.Classe')),
                ('groupe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp1', to='iscae_emploi.Groupe')),
                ('groupe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp2', to='iscae_emploi.Groupe')),
            ],
            options={
                'verbose_name_plural': 'Groupe Chevauchement',
                'unique_together': {('classe', 'groupe1', 'groupe2')},
            },
        ),
    ]
