# Generated by Django 3.0.8 on 2020-11-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_emploi', '0013_groupechevauchement'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='numero',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
